name: boring
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10.6
  - pip=22.2.2
  - pytorch
  - torchvision
  - numpy
  - pytorch-cuda=11.8
  - pip:
    - pytorch-lightning==1.8.0.post1
    - einops==0.5.0
    - transformers==4.26.1
    - k_diffusion==0.0.10
    - open_clip_torch==2.7.0
    - opencv-python==4.6.0.66
    - imutils==0.5.4
    - timm==0.6.12
    - omegaconf==2.1.1
    - invisible-watermark>=0.1.5
    - xformers==0.0.16
    - encodec
    - funcy
