import os
from core import samplers
from core.modules.clip import OpenCLIPEmbedder, PromptBuilder, CLIPEmbedder
from core.modules.vae_decoder import VAEDecoder
from core.modules.stable_diffusion_v2 import StableDiffusion
import models
from torch import autocast

def save_images(samples, material):
    directory = "outputs/Textures"
    if not os.path.exists(directory):
        os.makedirs(directory)    
    base_count = len(os.listdir(directory))
    for sample in samples:
        sample.save(os.path.join(directory, f"{material} {base_count:05}.png"))
        base_count += 1

def main():
    with autocast("cuda"):
        model = StableDiffusion(1, models.unet.SD1_5_fp32, parameterization="eps", tiling=True, use_fp16=True, device="cuda").cuda().half()
        decoder = VAEDecoder(models.decoder.VAEDec1_5mse_fp32, tiling=True).cuda()
        clip = CLIPEmbedder().cuda()
        negative_prompt = clip("glare, imperfections, ugly, cartoon, drawn, blurry")
        while True:
            for material in [
"80S Abstract Wallpaper",
"80S Animal Print Wallpaper",
"80S Art Deco Wallpaper",
"80S Boho Wallpaper",
"80S Camouflage Wallpaper",
"80S Checkered Wallpaper",
"80S Damask Wallpaper",
"80S Floral Wallpaper",
"80S Geometric Wallpaper",
"80S Graffiti Wallpaper",
"80S Graphic Wallpaper",
"80S Marble Wallpaper",
"80S Mosaic Wallpaper",
"80S Neon Wallpaper",
"80S Paisley Wallpaper",
"80S Plaid Wallpaper",
"80S Polka Dot Wallpaper",
"80S Pop Art Wallpaper",
"80S Rainbow Wallpaper",
"80S Retro Wallpaper",
"80S Space Wallpaper",
"80S Striped Wallpaper",
"80S Textured Wallpaper",
"80S Tile Wallpaper",
"80S Wood Panel Wallpaper",
"Abandoned Boat Remains",
"Abandoned Swamp Cabins",
"Abandoned Swamp Huts",
"Abandoned Swamp Machinery",
"Abandoned Swamp Mines",
"Abandoned Water Wells",
"Abstract 70S Wallpaper",
"Abstract Mosaic Wall",
"Abstract Pattern",
"Abstract Wall",
"Abstract Wallpaper",
"Acetate",
"Acrylic Fabric",
"Acrylic",
"Action Figures",
"Advertisements",
"Aerial Agricultural Landscape",
"Aerial Asphalt",
"Aerial Beach House",
"Aerial Beach Rocks",
"Aerial Beach Sunset",
"Aerial Beach View",
"Aerial Beach",
"Aerial Beachscape",
"Aerial Cityscape",
"Aerial Coastal Cliffs",
"Aerial Coastal Dunes",
"Aerial Coastal Landscape",
"Aerial Coastal Ocean",
"Aerial Coastal Sunset",
"Aerial Coastline",
"Aerial Countryside",
"Aerial Delta Island",
"Aerial Delta Landscape",
"Aerial Delta River",
"Aerial Delta Swamp",
"Aerial Desert Landscape",
"Aerial Farm Animals",
"Aerial Farm Barn",
"Aerial Farm Equipment",
"Aerial Farm Fields",
"Aerial Farm Horses",
"Aerial Farm Landscape",
"Aerial Farm Pond",
"Aerial Farm Silo",
"Aerial Farmstead",
"Aerial Forest Canopy",
"Aerial Forest Clearing",
"Aerial Forest Landscape",
"Aerial Forest Mist",
"Aerial Forest Trees",
"Aerial Forest View",
"Aerial Glacier Ice Cave",
"Aerial Glacier Ice",
"Aerial Glacier Landscape",
"Aerial Glacier River",
"Aerial Glacier View",
"Aerial Grass Rock",
"Aerial Ground Rock",
"Aerial Hill Clouds",
"Aerial Hill Range",
"Aerial Hill Shadows",
"Aerial Hill View",
"Aerial Hill Village",
"Aerial Hillside Farm",
"Aerial Hillside Sunset",
"Aerial Hillside View",
"Aerial Hilltop Farm",
"Aerial Hilltop View",
"Aerial Island Beach House",
"Aerial Island Beach",
"Aerial Island Landscape",
"Aerial Island Palm Trees",
"Aerial Island View",
"Aerial Jungle Canopy",
"Aerial Jungle Landscape",
"Aerial Jungle River Delta",
"Aerial Jungle River",
"Aerial Jungle Waterfall",
"Aerial Lake Cabin",
"Aerial Lake Mist",
"Aerial Lake Reflection",
"Aerial Lake Shore",
"Aerial Lake View From Above",
"Aerial Lake View",
"Aerial Mountain Cabin",
"Aerial Mountain Pass",
"Aerial Mountain Peak",
"Aerial Mountain Range",
"Aerial Mountain Ridge",
"Aerial Mountain Snow",
"Aerial Mountain Sunset",
"Aerial Mountain Top",
"Aerial Mountain Trail",
"Aerial Mountain View",
"Aerial Mountain Waterfall",
"Aerial Mud",
"Aerial Ocean Horizon",
"Aerial Ocean Sunset",
"Aerial Ocean View From Above",
"Aerial Ocean View",
"Aerial Ocean Waves",
"Aerial Park Flower Garden",
"Aerial Park Forest",
"Aerial Park Meadow",
"Aerial Park Picnic Area",
"Aerial Park View",
"Aerial River Landscape",
"Aerial Rocks",
"Aerial Sand",
"Aerial Urban Bridge",
"Aerial Urban Downtown",
"Aerial Urban Landscape",
"Aerial Urban Skyline",
"Aerial Urban Skyscrapers",
"Aerial Valley Farmland",
"Aerial Valley Floor",
"Aerial Valley Landscape",
"Aerial Valley Sunrise",
"Aerial Valley Sunset",
"Aerial Waterfall Landscape",
"Aerial Wood Snips",
"Aged Brass",
"Aged Steel",
"Aged Wood Flooring",
"Aged Wood",
"Aggregate Gravel",
"Aging Brass Panel",
"Alencon Lace Fabric",
"Algae Covered Stones",
"Alien Antenna Surface",
"Alien Blood Vessels",
"Alien Bone Structure",
"Alien Brain Matter",
"Alien Carapace",
"Alien Chitin",
"Alien Eyeball Surface",
"Alien Footpad Surface",
"Alien Muscle Tissue",
"Alien Pincer Surface",
"Alien Reproductive Organs",
"Alien Stinger Surface",
"Alien Tail Surface",
"Alien Tentacle Skin",
"Angular Gravel",
"Animal Pattern",
"Animal Wallpaper",
"Antimicrobial Fabric",
"Arabescato Marble",
"Ardex",
"Argyle Pattern",
"Argyle Wallpaper",
"Art Deco 70S Wallpaper",
"Art Deco Wall",
"Art Supplies, Such As Paint Tubes Or Watercolor Palettes",
"Ash Wood",
"Asphalt Floor",
"Asphalt",
"Athletic Fabric",
"Aztec Wallpaper",
"Azul Bahia Marble",
"Azul Macaubas Marble",
"Backsplash Wall",
"Bamboo Flooring",
"Bamboo Leaves",
"Bamboo Wallpaper",
"Bamboo Wood",
"Bamboo",
"Bark Brown",
"Bark Willow",
"Barn Wood",
"Baroque Wallpaper",
"Basalt Gravel",
"Basalt",
"Baseball Playground",
"Basket Weave Pattern",
"Batik Pattern",
"Battenburg Lace Fabric",
"Beads",
"Beam Wall",
"Beech Wood",
"Beige Wall",
"Bianco Lasa Marble",
"Biodegradable Fabric",
"Birch Bark",
"Birch Wood",
"Bird Wallpaper",
"Black And White Pattern",
"Black Hole",
"Black Wood",
"Blue Floor Tiles",
"Blue Painted Planks",
"Board Game Dice",
"Board Game Pieces",
"Boggy Ground",
"Bold 70S Wallpaper",
"Bold Wood",
"Bonded Fabric",
"Book Pages",
"Book Pattern",
"Bookmarks",
"Botanical Wallpaper",
"Botticino Marble",
"Bottle Caps",
"Boucle Fabric",
"Brick 70S Wallpaper",
"Brick Floor",
"Brick Flooring",
"Brick Moss",
"Brick Wall",
"Brick Wallpaper",
"Brick",
"Bright Sun Floor",
"Brisk Sand Floor",
"Brittle Tile Floor",
"Brocade Fabric",
"Broken Wall",
"Brown Brick",
"Brown Leather",
"Brown Mud Dry",
"Brown Mud Leaves",
"Brown Mud Rocks",
"Brown Mud",
"Brown Planks",
"Brushed Aluminum",
"Brushed Concrete",
"Brushed Steel",
"Brushed Wood",
"Building Blocks",
"Bulbous Toadstools",
"Bumpy Alien Hide",
"Bumpy Bark",
"Bumpy Concrete Wall",
"Bumpy Dirt Floor",
"Bumpy Rock",
"Bumpy Terrain",
"Bumpy Tree Bark Texture",
"Burned Ground",
"Burnished Steel",
"Burnished Wood",
"Burnt Wood",
"Business Cards",
"Butterfly Wallpaper",
"Buttons",
"Calacatta Marble",
"Calico Fabric",
"Cambric Fabric",
"Camouflage Wallpaper",
"Canvas Fabric",
"Canvas",
"Carabiners",
"Carpet",
"Carrara Marble",
"Carved Concrete Wall",
"Carved Stone Wall",
"Carved Wood",
"Carved Wooden Wall",
"Castle Brick Broken",
"Castle Brick Red",
"Castle Brick White",
"Castle Brick",
"Castle Stone Walls",
"Castle Wall Slates",
"Castle Wall Varriation",
"Cedar Bark",
"Cedar Branches",
"Cedar Wood",
"Celtic Knot Forest Floor",
"Celtic Knot Forest Trees",
"Celtic Knot Forest Vines",
"Celtic Knot Patterned Tiles",
"Celtic Knot Stone Walls",
"Celtic Knot Tiles",
"Cement Ground Textures",
"Cement Wall",
"Cement",
"Ceramic Floor Tiles",
"Ceramic Mosaic Ground Tiles",
"Ceramic Roof",
"Ceramic",
"Chantilly Lace Fabric",
"Charred Wood",
"Checkerboard 70S Wallpaper",
"Chenille Fabric",
"Cherry Blossom Petals",
"Cherry Wood",
"Chess Pieces",
"Chevron Pattern",
"Chevron Wall",
"Chevron Wallpaper",
"Chevron Wood",
"Chiffon Fabric",
"Chipped Magnesium",
"Chipped Metal Texture",
"Chipped Rock Texture",
"Chipped Stone Floor",
"Chipped Stone Texture",
"Choking Swamp Smoke",
"Chunky Mosaic Wall",
"Church Bricks",
"Circular Pattern",
"Clay Floor",
"Clean Pebbles",
"Cloud Wallpaper",
"Cloudy Night Floor",
"Cloudy Sky Floor",
"Cloudy Storm Floor",
"Coarse Brick Texture",
"Coarse Dirt Floor",
"Coarse Fur",
"Coarse Hair Texture",
"Coarse Hair",
"Coarse Rock Floor",
"Coarse Sand",
"Coarse Sandpaper",
"Coarse Sandstone Floor",
"Coast Land Rocks",
"Coast Sand Rocks",
"Coast Sand",
"Cobblestone Color",
"Cobblestone Floor",
"Cobblestone Gravel",
"Cobblestone Large",
"Cobblestone Square",
"Cobblestone Street Floor",
"Cobblestone",
"Coins",
"Coir",
"Color Block 70S Wallpaper",
"Color Block Pattern",
"Colored Ceramic Tiling",
"Colored Concrete Flooring",
"Colored Glass Wall",
"Colored Gravel",
"Colored Limestone Tiling",
"Colored Marble Flooring",
"Colored Mosaic Floor Tiles",
"Colored Pencils",
"Colored Sandstone Flooring",
"Colored Sandstone Tiling",
"Colored Slate Flooring",
"Colored Stone Wall",
"Colorful Wood",
"Comics Or Graphic Novels",
"Concrete Block Wall",
"Concrete Brick Wall",
"Concrete Floor Painted",
"Concrete Floor Worn",
"Concrete Floor",
"Concrete Tiling",
"Concrete Wall",
"Concrete",
"Confetti Pattern",
"Conifer Cones",
"Coral Fort Wall",
"Coral Gravel",
"Coral Ground",
"Coral Mud",
"Corduroy Fabric",
"Corduroy",
"Cork",
"Corroded Copper Plate",
"Corroded Metal Wall",
"Corroded Metal",
"Corroded Steel Wall",
"Cosmic Background Radiation",
"Cosmic Bubble",
"Cosmic Cluster",
"Cosmic Dust",
"Cosmic Filament",
"Cosmic Flows",
"Cosmic Microwave Background",
"Cosmic Radiation",
"Cosmic Rays",
"Cosmic Stream",
"Cosmic Structure",
"Cosmic Supercluster",
"Cosmic Void",
"Cosmic Wall",
"Cosmic Web",
"Cotton Fabric",
"Cotton",
"Cracked Asphalt Floor",
"Cracked Concrete Wall",
"Crackled Concrete",
"Crackled Ice",
"Crackled Wood",
"Creepy Crawly Critters",
"Crema Marfil Marble",
"Crepe Fabric",
"Crispy Leaves Texture",
"Crispy Paper Texture",
"Crooked Tree Trunks",
"Crumbled Brick Wall",
"Crumbled Concrete Wall",
"Crumbling Swamp Ruins",
"Crumbly Dirt Texture",
"Crushed Glass Wall",
"Crushed Gravel",
"Crushed Stone Wall",
"Crusty Bread Texture",
"Crusty Snow Texture",
"Crystal Wall",
"Damask Fabric",
"Damask Floral Wallpaper",
"Damask Pattern",
"Damask Wallpaper",
"Damp Moss Texture",
"Damp Paint Texture",
"Damp Soil Texture",
"Damp Wood Texture",
"Danby Marble",
"Dandelion Wallpaper",
"Dark Ash Floor",
"Dark Brick Wall",
"Dark Castle Stone Walls",
"Dark Dungeon Floor",
"Dark Forest Floor",
"Dark Matter",
"Dark Planks",
"Dark Swamp Shadows",
"Dark Walnut",
"Dark Water Shadows",
"Dark Water-Filled Potholes",
"Dark Wood",
"Dark Wooden Cabin Floor",
"Dark Wooden Dragon Ship Bowsprit",
"Dark Wooden Dragon Ship Mast",
"Dark Wooden Dragon Ship Walls",
"Dark Wooden Pirate Ship Deck",
"Decay And Rot",
"Decaying Tree Trunks",
"Decaying Wooden Floor",
"Decorative Brick Wall",
"Decorative Glass Wall",
"Decorative Gravel",
"Decorative Stone Wall",
"Decorative Tiled Floor",
"Decorative Wooden Wall",
"Defense Wall",
"Denim Fabric",
"Denim Wallpaper",
"Denim",
"Denmin Fabric",
"Dense Foggy Mist",
"Dense Misty Clouds",
"Dense Swamp Canopies",
"Dense Swamp Mist",
"Dented Iron Plate",
"Dented Metal Floor",
"Dented Metal Wall",
"Dented Steel Wall",
"Diamond Pattern",
"Diamond Plate Steel",
"Diamond Wall",
"Dice",
"Dirt Aerial",
"Dirt Floor",
"Dirty Brick Wall",
"Dirty Concrete",
"Dirty Glass Panel Wall",
"Dirty Glass Wall",
"Dirty Linoleum Floor",
"Dirty Oil Texture",
"Dirty Stucco Wall",
"Distant Swamp Howls",
"Distant Swamp Sounds",
"Distressed Iron",
"Distressed Wood Floor Tiles",
"Distressed Wood Wall",
"Distressed Wood",
"Dogwood Branches",
"Dogwood Flowers",
"Doll Parts",
"Dollhouse Furniture",
"Dot Pattern",
"Dotted Swiss Fabric",
"Dotted Wallpaper",
"Down",
"Dragon Claw Marks",
"Dragon Fire And Ash",
"Dragon Fire And Scales",
"Dragon Fire And Smoke",
"Dragon Fire Tiles",
"Dragon Hoard Tiles",
"Dragon Scale Tiles",
"Dragon Scales And Fire",
"Dragon Skin Tiles",
"Dragonfly Wallpaper",
"Drainage Gravel",
"Drapery Fabric",
"Driftwood",
"Dripping Wet Texture",
"Driveway Gravel",
"Dry Ground Rocks",
"Dry Ground",
"Dry Mud Field",
"Dull Concrete Texture",
"Dull Metal Wall",
"Dull Metal",
"Dull Steel",
"Eased Wood",
"Eco-Friendly Fabric",
"Elastomeric",
"Elegant Marble Floor",
"Elm Wood",
"Embossed Wall",
"Embossed Wallpaper",
"Embossed Wood",
"Embroidered Fabric",
"Embroidered Rug Floor",
"Emperador Dark Marble",
"Enchanted Forest Floor",
"Enchanted Garden Flowers",
"Enchanted Garden Pathway",
"Enchanted Garden Plants",
"Enchanted Garden Trees",
"Enchanted Garden Waterfall",
"Enchanted Rose Garden Tiles",
"Enchanted Rose Petals",
"Enchanted Tree Bark",
"Enchanted Tree Branches",
"Enchanted Tree Leaves",
"Enchanted Tree Roots",
"Enchanted Vine Tiles",
"Enchanted Waterfall Tiles",
"Engineered Concrete Flooring",
"Engineered Stone Flooring",
"Engineered Wood Ground Tiles",
"Engineered Wood",
"Enormous Swamp Trees",
"Envelopes",
"Epoxy",
"Erasers",
"Eroded Concrete Wall",
"Eroded Stone Wall",
"Etched Glass Wall",
"Etched Steel",
"Etched Stone Panel Wall",
"Etched Stone Wall",
"Ethnic 70S Wallpaper",
"Eye-Catching 70S Wallpaper",
"Eyelet Fabric",
"Fabric Leather",
"Fabric Pattern",
"Fabric Wallpaper",
"Fabric",
"Factory Brick",
"Factory Wall",
"Faded Brick Wall",
"Faded Gold",
"Faded Linoleum Floor",
"Faded Paint Wall",
"Faded Paper",
"Faded Stucco Wall",
"Faded Wallpaper Floor",
"Faded Wallpaper Wall",
"Faded Wallpaper",
"Fairy Dust Tiles",
"Fairy Tale Castle Battlements",
"Fairy Tale Castle Door",
"Fairy Tale Castle Entrance",
"Fairy Tale Castle Roof",
"Fairy Tale Castle Tower",
"Fairy Tale Castle Walls",
"Fairy Tale Castle Window",
"Fairy Wing Patterns",
"Fallen Leaves",
"Fantasy Forest Floor",
"Fantasy Forest Flowers",
"Fantasy Forest Trees",
"Fantasy Forest Vines",
"Fantasy Forest Water",
"Fantasy Stone Walls",
"Faux Brick",
"Faux Concrete",
"Faux Granite",
"Faux Limestone",
"Faux Marble",
"Faux Metal",
"Faux Mosaic",
"Faux Stone Wall",
"Faux Stone",
"Faux Terrazzo",
"Faux Travertine",
"Faux Wood",
"Feather Wallpaper",
"Feather",
"Felt Shapes",
"Fern And Daisies On Stones",
"Fern And Daisies",
"Fern And Grasses",
"Fern And Lichen",
"Fern And Moss",
"Fern And Mushrooms",
"Fern And Pine Cones",
"Fern And Poppies",
"Fern And Wildflowers",
"Fern Fronds",
"Fern Spores On Rocks",
"Fern Spores",
"Fern, Daisies, And Lichen",
"Fern, Daisies, And Moss",
"Fern, Grasses, And Daisies",
"Fern, Grasses, And Wildflowers",
"Fern, Moss, And Lichen",
"Fern, Moss, And Stones",
"Fern, Mushrooms, And Birch Bark",
"Fern, Mushrooms, And Cedar Branches",
"Fern, Mushrooms, And Conifer Cones",
"Fern, Mushrooms, And Daisies",
"Fern, Mushrooms, And Fallen Leaves",
"Fern, Mushrooms, And Fern And Birch Bark",
"Fern, Mushrooms, And Fern And Ivy Vines",
"Fern, Mushrooms, And Fern And Maple Leaves",
"Fern, Mushrooms, And Fern And Oak Leaves",
"Fern, Mushrooms, And Fern And Pine Cones",
"Fern, Mushrooms, And Fern Fragments On Rocks",
"Fern, Mushrooms, And Fern Fragments",
"Fern, Mushrooms, And Fern Fronds",
"Fern, Mushrooms, And Fern, Moss, And Lichen",
"Fern, Mushrooms, And Fern, Moss, And Stones",
"Fern, Mushrooms, And Forest Floor Debris",
"Fern, Mushrooms, And Grasses",
"Fern, Mushrooms, And Ivy Vines",
"Fern, Mushrooms, And Lichen",
"Fern, Mushrooms, And Maple Branches",
"Fern, Mushrooms, And Maple Leaves",
"Fern, Mushrooms, And Moss And Lichen",
"Fern, Mushrooms, And Moss And Stones",
"Fern, Mushrooms, And Moss",
"Fern, Mushrooms, And Oak Leaves",
"Fern, Mushrooms, And Pine Branches",
"Fern, Mushrooms, And Pine Cones",
"Fern, Mushrooms, And Poppies",
"Fern, Mushrooms, And Stones And Pebbles",
"Fern, Mushrooms, And Stones",
"Fern, Mushrooms, And Wildflowers",
"Fern, Poppies, And Daisies",
"Fern, Poppies, And Grasses",
"Fern, Poppies, And Lichen",
"Fern, Poppies, And Moss",
"Fern, Poppies, And Wildflowers",
"Fern, Wildflowers, And Lichen",
"Fern, Wildflowers, And Moss",
"Fiery Flames",
"Fine Grained Wood",
"Fire Dragon Breath",
"Fire Resistant Fabric",
"Flaky Paint Texture",
"Flannel Fabric",
"Fleece Fabric",
"Fleece Wallpaper",
"Fleece",
"Floating Swamp Debris",
"Floating Swamp Lily Pads",
"Floating Swamp Logs",
"Floating Water Hyacinths",
"Floating Water Lilies",
"Floor Bricks",
"Floor Klinkers",
"Floor Pattern",
"Floor Pavement",
"Floor Pebbles",
"Floor Tiles",
"Floral 70S Wallpaper",
"Floral Pattern",
"Floral Wallpaper",
"Flowing Lava",
"Fluffy Carpet Floor",
"Fluffy Cloud Floor",
"Fluffy Clouds",
"Fluffy Cotton Balls",
"Fluffy Cotton Candy",
"Fluffy Cotton",
"Fluffy Feather Floor",
"Fluffy Feathers",
"Fluffy Fur Texture",
"Fluffy Fur",
"Foam",
"Foil Wallpaper",
"Forest Floor Debris",
"Forest Floor Leaves",
"Forest Floor",
"Forest Ground",
"Forest Leaves",
"Forrest Ground",
"Forrest Sand",
"Foul Smelling Mud Holes",
"Foul Swamp Odors",
"Fractured Glass Texture",
"Frayed Rug Floor",
"French Lace Fabric",
"Fur",
"Fused Fabric",
"Futuristic 70S Wallpaper",
"Fuzzy Alien Coating",
"Fuzzy Carpet Floor",
"Fuzzy Carpet Texture",
"Fuzzy Caterpillar",
"Fuzzy Fur Floor",
"Fuzzy Fur",
"Fuzzy Green Moss",
"Fuzzy Moss",
"Fuzzy Spider Webs",
"Fuzzy Wool Texture",
"Fuzzy Wool",
"Galactic Gas",
"Galaxies",
"Galvanized Steel",
"Garden Wallpaper",
"Gauze Fabric",
"Geometric 70S Wallpaper",
"Geometric Mosaic Wall",
"Geometric Pattern",
"Geometric Wall",
"Geometric Wallpaper",
"Gingham Fabric",
"Gingham Pattern",
"Glass Art Wall",
"Glass Bead Wallpaper",
"Glass Fibers",
"Glass Floor Textures",
"Glass Hex Wall",
"Glass Mosaic Wall",
"Glass Pebble Wall",
"Glass Subway Wall",
"Glass Wall",
"Glass",
"Glassy Crystal",
"Glassy Diamonds",
"Glassy Gem Texture",
"Glassy Ice",
"Glassy Ocean Floor",
"Glassy Surface Floor",
"Glassy Wall",
"Glaze Wallpaper",
"Glimmering Fairy Lights",
"Glistening Crystal Floor",
"Glistening Ice Texture",
"Glistening Oil Texture",
"Glistening Snow Floor",
"Glistening Sweat Texture",
"Glistening Water Floor",
"Glitter Wall",
"Glitter Wallpaper",
"Glittering Gold Floor",
"Glittering Gold Texture",
"Glitz Wall",
"Gloomy Dungeon Floor",
"Gloomy Forest Floor",
"Gloomy Mist Floor",
"Gloomy Moss Texture",
"Gloomy Swamp Floor",
"Glossy Plastic",
"Glowing Alien Material",
"Glowing Auroras",
"Glowing Candlelight Texture",
"Glowing Crystal Floor",
"Glowing Embers Texture",
"Glowing Energy",
"Glowing Eyes",
"Glowing Fairy Dust Tiles",
"Glowing Fairy Tale Moon",
"Glowing Fairy Tale Sky",
"Glowing Fairy Tale Stars",
"Glowing Fairy Tale Sun",
"Glowing Fire Floor",
"Glowing Fire Texture",
"Glowing Fireflies",
"Glowing Firefly Texture",
"Glowing Lantern Texture",
"Glowing Lava Floor",
"Glowing Lava Texture",
"Glowing Light Bulb Texture",
"Glowing Light Texture",
"Glowing Magic Runes",
"Glowing Moon Tiles",
"Glowing Mushroom Floor",
"Glowing Mushrooms",
"Glowing Neon Texture",
"Glowing Neon",
"Glowing Rainbow Floor",
"Glowing Runes",
"Glowing Star Tiles",
"Glowing Swamp Lights",
"Gnarled Swamp Roots",
"Gneiss",
"Gold Leaf Wallpaper",
"Gothic Wall",
"Graffiti-Covered Wall",
"Graffiti-Tagged Wall",
"Granite Flooring",
"Granite Gravel",
"Granite Mosaic Tiles",
"Granite",
"Granny Square 70S Wallpaper",
"Granodiorite",
"Granular Concrete",
"Grass Path",
"Grasscloth Wallpaper",
"Grasscloth",
"Grassy Cobblestone",
"Gravel Concrete",
"Gravel Ground",
"Gray Wood",
"Greek Key Pattern",
"Green Metal Rust",
"Green Onyx Marble",
"Green Rough Planks",
"Grey Plaster",
"Grey Roof Tiles",
"Grey Roof",
"Grim Concrete Floor",
"Grimy Carpet Floor",
"Gritty Concrete Floor",
"Gritty Concrete Wall",
"Gritty Sand Texture",
"Gritty Stone",
"Grommet Wallpaper",
"Grooved Wood",
"Groovy 70S Wallpaper",
"Ground Grey",
"Grungy Brick Wall",
"Grungy Concrete Floor",
"Grungy Glass Wall",
"Grungy Zinc",
"Guipure Lace Fabric",
"Hair Ties",
"Half-Submerged Logs",
"Hammered Steel",
"Hangers",
"Haunting Swamp Whispers",
"Hay",
"Hazy Clouds",
"Hazy Fog Floor",
"Hazy Fog",
"Hazy Mist",
"Hazy Smoke Texture",
"Hazy Smoke",
"Hazy Wood",
"Hdpe",
"Hemp",
"Herringbone Fabric",
"Herringbone Pattern",
"Herringbone Wall",
"Herringbone Wallpaper",
"Herringbone Wood",
"Hex Wall",
"Hexagon Mosaic Wall",
"Hexagonal Concrete Paving",
"Hexagonal Floor Tiles",
"Hexagonal Mosaic Floor Tiles",
"Hexagonal Terrazzo Tiling",
"Hexagonal Wall",
"Hidden Swamp Caves",
"High Gloss Wood",
"Highlighters",
"Holographic Alien Texture",
"Honed Wood",
"Houndstooth Fabric",
"Houndstooth Pattern",
"Ice Palace Walls",
"Ikat Pattern",
"Ikat Wallpaper",
"Industrial Concrete Flooring",
"Industrial Glass Wall",
"Industrial Steel Wall",
"Industrial Stone Ground Tiles",
"Industrial Wall",
"Insulated Fabric",
"Interstellar Clouds",
"Intricate Concrete Wall",
"Intricate Lace",
"Intricate Metal Wall",
"Intricate Stone Wall",
"Intricate Wooden Wall",
"Iridescent Alien Surface",
"Iridescent Glass Floor",
"Iridescent Scales",
"Iridescent Wall",
"Irish Chain Pattern",
"Ivy Vines",
"Jacobean Pattern",
"Jacquard Fabric",
"Jacquard Wallpaper",
"Jagged Rock Floor",
"Japanese Stone Wall",
"Jersey Fabric",
"Jigsaw Puzzle Pieces",
"Jungle Pattern",
"Jungle Wallpaper",
"Jute",
"Kaleidoscope Wallpaper",
"Key Rings",
"Kitchen Wood",
"Kitschy 70S Wallpaper",
"K'Nex Pieces",
"Knit Fabric",
"Knit Wallpaper",
"Knotty Wood",
"Labels",
"Lace Fabric",
"Lace Wallpaper",
"Laminate Floor",
"Laminate",
"Laminated Fabric",
"Landscaping Gravel",
"Large Floor Tiles",
"Large Gravel",
"Large Grey Tiles",
"Large Red Bricks",
"Large Sandstone Blocks",
"Large Square Pattern",
"Lattice Pattern",
"Lava Gravel",
"Ldpe",
"Leaf Pattern",
"Leather Red",
"Leather Wall",
"Leather Wallpaper",
"Leather White",
"Leather",
"Leaves Forest Ground",
"Lego Pieces",
"Leopard Print Pattern",
"Light Oak",
"Lightweight Feathers",
"Limestone Gravel",
"Limestone Ground Tiles",
"Limestone Wall",
"Limestone",
"Line Pattern",
"Linen Fabric",
"Linen Wallpaper",
"Linen",
"Lingerie Fabric",
"Linoleum",
"Loom Woven Pattern",
"Magazine Clippings",
"Magazine Covers",
"Magic Castle Door",
"Magic Castle Entrance",
"Magic Castle Roof",
"Magic Castle Tower",
"Magic Castle Walls",
"Magic Castle Window",
"Magic Mushroom Tiles",
"Mahogany Wood",
"Mangled Fishing Nets",
"Maple Bark",
"Maple Branches",
"Maple Leaves And Seeds",
"Maple Leaves",
"Maple Wood",
"Maps",
"Marble Floor Textures",
"Marble Gravel",
"Marble Mosaic Wall",
"Marble Wall",
"Marble Wallpaper",
"Marble",
"Marbled Stone Texture",
"Marbles",
"Markers",
"Marred Stainless Steel",
"Marshy Fields Of Grass",
"Matelassé Fabric",
"Matte Steel",
"Matte Wood",
"Mdf",
"Medallion Pattern",
"Medallion Wallpaper",
"Medieval Blocks",
"Medieval Wall",
"Medieval Wood",
"Melamine",
"Mermaid Lagoon Coral",
"Mermaid Lagoon Plants",
"Mermaid Lagoon Rocks",
"Mermaid Lagoon Sand",
"Mermaid Lagoon Tiles",
"Mermaid Scales Tiles",
"Mermaid Tail Scales",
"Mesh Fabric",
"Metal Grate Rusty",
"Metal Mosaic Wall",
"Metal Plate",
"Metal Wall",
"Metal",
"Meteor Wallpaper",
"Microfiber Wallpaper",
"Mid-Century 70S Wallpaper",
"Miniature Figurines",
"Mirror Mosaic Wall",
"Mirror Wall",
"Mix And Match Wood",
"Mixed Gravel",
"Mixed Woods",
"Mod 70S Wallpaper",
"Modern Wall",
"Moisture-Wicking Fabric",
"Monochromatic Wood",
"Mosaic Art Wall",
"Mosaic Brick Wall",
"Mosaic Cement Wall",
"Mosaic Chevron Wall",
"Mosaic Concrete Block Wall",
"Mosaic Concrete Wall",
"Mosaic Floor Tiles",
"Mosaic Glass Subway Wall",
"Mosaic Glass Wall",
"Mosaic Herringbone Wall",
"Mosaic Hex Wall",
"Mosaic Hexagonal Wall",
"Mosaic Limestone Flooring",
"Mosaic Limestone Tiling",
"Mosaic Limestone Wall",
"Mosaic Marble Wall",
"Mosaic Metal Wall",
"Mosaic Mirror Wall",
"Mosaic Pattern",
"Mosaic Pebble Stone Flooring",
"Mosaic Porcelain Wall",
"Mosaic Quarry Wall",
"Mosaic Random Wall",
"Mosaic Sandstone Wall",
"Mosaic Stacked Stone Wall",
"Mosaic Stone Wall",
"Mosaic Terrazzo Flooring",
"Mosaic Terrazzo Ground Tiles",
"Mosaic Terrazzo Wall",
"Mosaic Textured Wall",
"Mosaic Tiled Floor",
"Mosaic Tiled Wall",
"Mosaic Travertine Flooring",
"Mosaic Travertine Wall",
"Mosaic Wall",
"Mosaic Wallpaper",
"Mosaic Wave Wall",
"Mosaic Wood Subway Wall",
"Mosaic Wood Wall",
"Mosaic Wood",
"Mosaic",
"Mosaic-Tiled Wall",
"Moss And Lichen",
"Moss And Stones",
"Moss Wood",
"Moss",
"Mossy Rock",
"Mossy Rocks",
"Mottled Concrete Floor",
"Mottled Tree Bark",
"Mud Cracked Dry Riverbed",
"Mud Cracked Dry",
"Muddy Dirt Floor",
"Muddy Dirt",
"Muddy Ground",
"Multi-Tone Wood",
"Mural Wallpaper",
"Mural",
"Murky Swamp Reflections",
"Murky Swampland Puddles",
"Murky Water Reflections",
"Muslin Fabric",
"Mylar Wallpaper",
"Mysterious Swamp Sounds",
"Mythical Creature Tracks",
"Narrow Winding Channels",
"Natural Ceramic Tiling",
"Natural Fabric",
"Natural Limestone Floor Tiles",
"Natural Rubber",
"Natural Stone Floor Mosaics",
"Natural Stone Mosaic Tiling",
"Natural Stone Wall",
"Natural Terrazzo Flooring",
"Natural Terrazzo Tiling",
"Natural Wood Floor Textures",
"Natural Wood",
"Nature Wallpaper",
"Nautical Pattern",
"Nautical Wallpaper",
"Nebula",
"Neoprene Fabric",
"Neoprene",
"Nero Marquina Marble",
"Nero Portoro Marble",
"Neutral Wood",
"Newspaper Clippings",
"Non-Woven Fabric",
"Non-Woven Wallpaper",
"Nuts And Bolts",
"Nylon Fabric",
"Nylon",
"Oak Leaves And Acorns",
"Oak Leaves",
"Oak Wood",
"Old Brick Wall",
"Old Planks",
"Old Wood Floor",
"Old Wooden Door Texture",
"Ombre Pattern",
"Ombre Wall",
"Ombre Wallpaper",
"Onyx",
"Organza Fabric",
"Origami",
"Ornament Wall",
"Ornate 70S Wallpaper",
"Ornate Brick Wall",
"Ornate Wall",
"Outdoor Fabric",
"Overgrown Roots And Vines",
"Overgrown Swamp Trees",
"Overgrown Swamp Underbrush",
"Overgrown Vines And Creepers",
"Overhanging Swamp Vines",
"Overhanging Willow Trees",
"Paint Brushes",
"Paint Splatter Wallpaper",
"Paint",
"Painted Concrete Wall",
"Painted Concrete",
"Painted Metal Shutter",
"Painted Metal Wall",
"Painted Steel",
"Painted Stone Wall",
"Painted Wall",
"Painted Wooden Wall",
"Paisley 70S Wallpaper",
"Paisley Pattern",
"Palm Tree Bark",
"Palm Tree Wallpaper",
"Paper Airplanes",
"Paper Boats",
"Paper Chains",
"Paper Clips In The Form Of Letters Or Numbers",
"Paper Clips Of Different Shapes And Sizes",
"Paper Flowers",
"Paper Lanterns",
"Paper Wallpaper",
"Papyrus",
"Park Dirt",
"Park Sand",
"Parquet Wood",
"Particleboard",
"Pastel Wood",
"Patchwork Pattern",
"Patchwork Wood",
"Patterned Brick Wall",
"Patterned Clay Wall",
"Pavement",
"Pea Gravel",
"Peacock Wallpaper",
"Pearl Wall",
"Pearl Wallpaper",
"Pebble Cemented Floor",
"Pebble Ground",
"Pebble Stone Tiling",
"Pebble Wall",
"Peeled Steel",
"Peeling Lead",
"Peeling Paint Panel Wall",
"Peeling Paint Wall",
"Peeling Wallpaper Floor",
"Peeling Wallpaper Wall",
"Pens",
"Perforated Steel",
"Performance Fabric",
"Photo Wallpaper",
"Photography Film Strips",
"Pine Branches",
"Pine Cones And Needles",
"Pine Needles",
"Pine Wood",
"Pineapple Wallpaper",
"Pins",
"Pitted Metal Floor",
"Pitted Metal Wall",
"Pitted Nickel",
"Pitted Steel Wall",
"Plaid Fabric",
"Plaid Wallpaper",
"Plank Flooring",
"Planks Brown",
"Plaster Brick",
"Plaster Grey",
"Plaster",
"Plastic Balls",
"Plastic Building Blocks",
"Plastic Containers",
"Plastic Cups",
"Plastic Cutlery",
"Plastic Flowers",
"Plastic Fruit Or Vegetables",
"Plastic Toys Or Figurines",
"Plastic Wallpaper",
"Plastic",
"Playing Card Suits",
"Playing Cards",
"Plush Fabric",
"Plywood",
"Polaroid Photos",
"Polished Marble Wall",
"Polished Steel",
"Polished Wood",
"Polished Wooden Floor",
"Polka Dot Fabric",
"Polka Dot Pattern",
"Polka Dot Wallpaper",
"Polluted Swamp Streams",
"Polluted Water Rivulets",
"Polycarbonate",
"Polyester Fabric",
"Polyester",
"Polyfill",
"Polypropylene",
"Polystyrene",
"Polyurethane",
"Poplin Fabric",
"Porcelain Tiling",
"Porcelain Wall",
"Porcelain",
"Porous Stone",
"Postage Stamps",
"Preconcrete Wall Long",
"Preconcrete Wall",
"Psychedelic 70S Wallpaper",
"Punch-Out Confetti",
"Push Pins",
"Pvc Wallpaper",
"Pvc",
"Quarry Wall",
"Quarry",
"Quartz Gravel",
"Quartz",
"Quatrefoil Pattern",
"Quatrefoil Wallpaper",
"Quilted Fabric",
"Raccoon Pattern",
"Ragged Brick Wall",
"Ragged Carpet Floor",
"Ragged Cloth Texture",
"Ragged Concrete Wall",
"Ragged Metal Wall",
"Ragged Paper Texture",
"Ragged Stonework Wall",
"Ragged Swamp Bushes",
"Ragged Swamp Foliage",
"Rainbow Wallpaper",
"Rainbow Wood",
"Rainforest Green Marble",
"Raked Dirt",
"Random Bricks Thick",
"Random Wall",
"Rattan",
"Rayon Fabric",
"Rayon",
"Receipts",
"Recipe Cards",
"Reclaimed Wood Wallpaper",
"Reclaimed Wood",
"Recycled Fabric",
"Red Brick Plaster Patch",
"Red Brick",
"Red Bricks",
"Red Dirt Mud",
"Red Laterite Soil Stones",
"Red Mud Stones",
"Red Onyx Marble",
"Red Plaster Weathered",
"Red Slate Roof Tiles",
"Redwood Wood",
"Reed Roof",
"Reed",
"Reeds And Rushes",
"Reflective Alien Surface",
"Reflective Diamonds",
"Reflective Glass",
"Reflective Metal",
"Reflective Mirrors",
"Reflective Water",
"Repeat Pattern",
"Resin",
"Retro 70S Wallpaper",
"Rhombus Wallpaper",
"Rhyolite",
"Ribbed Fabric",
"Riet",
"Ripped Steel",
"Rippled Water Floor",
"River Gravel",
"River Rock Wall",
"River Rock Wallpaper",
"River Small Rocks",
"Rock Boulder Cracked",
"Rock Boulder Dry",
"Rock Ground",
"Rock Pitted Mossy",
"Rock Wall",
"Rock",
"Rocks Ground",
"Rocky Trail",
"Roof Slates",
"Roof Tiles",
"Roof",
"Roots",
"Rosa Portogallo Marble",
"Rose Wallpaper",
"Rosewood Marble",
"Rotted Tin Sheet",
"Rotten Wood Planks",
"Rotten Wooden Floor",
"Rotting Boat Wrecks",
"Rough Bark Texture",
"Rough Bark",
"Rough Block Wall",
"Rough Brick Wall",
"Rough Concrete Texture",
"Rough Concrete Wall",
"Rough Concrete",
"Rough Gravel",
"Rough Plaster Brick",
"Rough Plaster Broken",
"Rough Plaster",
"Rough Plasterbrick",
"Rough Rock",
"Rough Sandstone",
"Rough Stone Texture",
"Rough Stucco Wall",
"Rough Wood",
"Roughened Metal Texture",
"Roughened Sand Texture",
"Roughened Steel",
"Roughened Stone Floor",
"Roughened Wood Texture",
"Roughened Wood",
"Round Gravel",
"Rubber Ducks",
"Rubber",
"Rubik'S Cube Squares",
"Running Track",
"Rust Coarse",
"Rust-Covered Floor",
"Rusted Iron",
"Rusted Metal Panel Wall",
"Rusted Steel Wall",
"Rusted Tin",
"Rustic Concrete Floor Tiles",
"Rustic Earth Ground Tiles",
"Rustic Limestone Floor Tiles",
"Rustic Limestone Mosaic Tiling",
"Rustic Marble Flooring",
"Rustic Mosaic Floor Tiles",
"Rustic Mosaic Ground Tiles",
"Rustic Mosaic Terra",
"Rustic Slate Ground Tiles",
"Rustic Steel",
"Rustic Stone Floor Tiles",
"Rustic Stone Wall",
"Rustic Terrazzo Ground Tiles",
"Rustic Wall",
"Rustic Wood Flooring",
"Rustic Wood",
"Rusting Metal Objects",
"Rusting Swamp Gates",
"Rusting Swamp Machinery",
"Rusty Metal Floor",
"Rusty Metal Grate",
"Rusty Metal Panel Wall",
"Rusty Metal Texture",
"Rusty Metal Wall",
"Rusty Metal",
"Rusty Steel Wall",
"Rusty Swamp Equipment",
"Safety Pins",
"Sand",
"Sand-Blasted Concrete Tiling",
"Sandblasted Steel",
"Sand-Blasted Stone Flooring",
"Sandblasted Wood",
"Sandstone Blocks",
"Sandstone Brick Wall",
"Sandstone Cracks",
"Sandstone Flooring",
"Sandstone Gravel",
"Sandstone Mosaic Floor Tiles",
"Sandstone Mosaic Tiling",
"Sandstone Wall",
"Sandstone Wallpaper",
"Sandstone",
"Sateen Fabric",
"Satin Fabric",
"Satin Wood",
"Sawn Wood",
"Sbr",
"Scallop Wallpaper",
"Scaly Alien Skin",
"Scaly Dragon Skin Texture",
"Scattered Brick Wall",
"Scattered Leaves And Twigs",
"Scattered Swamp Debris",
"Schist",
"Scissors",
"Scorched Earth Floor",
"Scored Wood",
"Scraped Wood",
"Scraps Of Paper Or Cardboard",
"Scratched Chrome",
"Scratched Glass Wall",
"Scratched Metal Wall",
"Scratched Steel",
"Screws",
"Scroll Pattern",
"Scuba Fabric",
"Scuffed Aluminum Alloy",
"Scuffed Leather Floor",
"Seagrass",
"Seagull Wallpaper",
"Sealed Wood",
"Seaweed Pattern",
"Seersucker Fabric",
"Sheer Fabric",
"Sheet Music",
"Shell Floor",
"Shell Pattern",
"Shell Wallpaper",
"Shimmer Wall",
"Shimmering Butterfly Wings",
"Shimmering Dragonflies",
"Shimmering Gold",
"Shimmering Hair",
"Shimmering Light Floor",
"Shimmering Moon Floor",
"Shimmering Sequins",
"Shimmering Silk Texture",
"Shimmering Silk",
"Shimmering Skin",
"Shimmering Starlight Texture",
"Shimmering Starry Sky Floor",
"Shimmering Swamp Crystals",
"Shimmering Swamp Fireflies",
"Shimmering Swamp Mirrors",
"Shimmering Swamp Moonlight",
"Shimmering Swamp Water",
"Shiny Chrome",
"Shiny Coins",
"Shiny Glass Floor",
"Shiny Glass Texture",
"Shiny Metal Texture",
"Shiny Metal",
"Shiny Silver",
"Shou Sugi Ban Wood",
"Silicone",
"Silk Fabric",
"Silk Wallpaper",
"Silk",
"Silky Cloth Floor",
"Silky Satin Texture",
"Silky Silk Floor",
"Silky Smooth Wall",
"Silky Water Floor",
"Silvery Metal Floor",
"Sisal",
"Skeletal Tree Branches",
"Skyscraper Wallpaper",
"Slab Tiles",
"Slate Ground Tiles",
"Slate Wall",
"Slate",
"Sleek Tile Floor",
"Slick Ice Floor",
"Slimy Alien Surface",
"Slimy Swamp Scum",
"Slimy Tentacles",
"Small Gravel",
"Small Paper Cups",
"Smoked Wood",
"Smoky Ash Floor",
"Smooth Glass Floor",
"Smooth Glass Panel Wall",
"Smooth Glass Wall",
"Smooth Ice Texture",
"Smooth Marble Floor",
"Smooth Metal Wall",
"Smooth Plastic Texture",
"Smooth Skin",
"Smooth Steel",
"Smooth Stone Panel Wall",
"Smooth Stone Texture",
"Smooth Stone Wall",
"Smooth Stone",
"Smooth Stucco Wall",
"Smoothed Sandstone Wall",
"Snapshots",
"Snow Field Aerial",
"Snow",
"Snowflake Tiles",
"Snowflake Wallpaper",
"Snowy Forest Floor",
"Snowy Ice Floor",
"Snowy Mountain Pass",
"Snowy Mountain Peak",
"Snowy Mountain Peaks",
"Snowy Mountain Range",
"Snowy Mountain Side",
"Soapstone",
"Soft Cashmere",
"Soft Cloth",
"Soft Cotton Texture",
"Soft Feathers Texture",
"Soft Feathers",
"Soft Fur Floor",
"Soft Fur Texture",
"Soft Fur",
"Soft Grass Floor",
"Soft Grass",
"Soft Moss Floor",
"Soft Sand Floor",
"Soft Silk Texture",
"Soft Suede Texture",
"Soft Velvet Texture",
"Soft Velvet",
"Solar Flares",
"Solid Wallpaper",
"Soot-Covered Floor",
"Sooty Fireplace Floor",
"Spalted Wood",
"Spandex Fabric",
"Sparkling Aurora Floor",
"Sparkling Crystals Texture",
"Sparkling Diamond Floor",
"Sparkling Diamond Texture",
"Sparkling Diamonds",
"Sparkling Fireworks",
"Sparkling Gem Floor",
"Sparkling Gems",
"Sparkling Glitter Texture",
"Sparkling Lights",
"Sparkling Sequins Texture",
"Sparkling Snowflakes",
"Sparkling Stars",
"Sparkling Swamp Water Droplets",
"Spell Book Cover Texture",
"Spell Book Pages",
"Spiky Alien Armor",
"Spiky Rock Floor",
"Spiky Thistle Texture",
"Spiky Vegetation",
"Sponge",
"Square Concrete Pavers",
"Square Floor Patern",
"Square Floor",
"St. Cecilia Marble",
"Stacked Rubber Bands",
"Stacked Stone Wall",
"Stained Concrete Floor",
"Stained Concrete Wall",
"Stained Glass Panel Wall",
"Stained Glass Wall",
"Stained Silver",
"Stained Tile Floor",
"Stained Wood",
"Stamped Postcards",
"Stamps",
"Staple Removers",
"Starfish Wallpaper",
"Starry Night Sky",
"Statuario Marble",
"Steel Plate",
"Stenciled Wood",
"Stickers",
"Sticky Honey Texture",
"Sticky Honey",
"Sticky Note Shapes, Such As Hearts Or Stars",
"Sticky Resin Texture",
"Sticky Sap Texture",
"Sticky Sap",
"Sticky Tar Texture",
"Sticky Tar",
"Stiff Cardboard Texture",
"Stiff Hair Texture",
"Stiff Leather Texture",
"Stiff Straw Texture",
"Stippled Wood",
"Stone Block Wall",
"Stone Brick Wall",
"Stone Brick Wallpaper",
"Stone Floor Mosaics",
"Stone Floor Textures",
"Stone Look Ceramic Tiling",
"Stone Mosaic Flooring",
"Stone Tiles",
"Stone Wall",
"Stone Wallpaper",
"Stone",
"Stones And Pebbles",
"Stony Cave Floor",
"Straw",
"Stretch Fabric",
"Stripe Wallpaper",
"Striped 70S Wallpaper",
"Striped Fabric",
"Striped Pattern",
"Strips Of Ribbon Or Fabric",
"Stucco",
"Sturdy Metal",
"Sturdy Stone Floor",
"Sturdy Stone",
"Sturdy Wood",
"Subway Tile Wall",
"Subway Wall",
"Suede Wallpaper",
"Suede",
"Sun-Baked Sand Floor",
"Sunbrella Fabric",
"Sunburst Pattern",
"Sun-Dappled Swamp Water",
"Sun-Drenched Swamp Water",
"Sunflower Wallpaper",
"Sunken Swamp Tree Stumps",
"Superhero Wallpaper",
"Supernova Remnant",
"Suspicious Green Slime",
"Suspicious Swamp Creatures",
"Sustainable Fabric",
"Swampy Ground Cracks",
"Swarming Insects",
"Swimwear Fabric",
"Swirl 70S Wallpaper",
"Swirl Pattern",
"Swirl Wall",
"Swirl Wallpaper",
"Swirling Swamp Currents",
"Synthetic Fabric",
"Synthetic Fill",
"Synthetic Gravel",
"Synthetic Rubber",
"Synthetic Wallpaper",
"Synthetic Wood",
"T Brick Floor",
"T Concrete Wall",
"Taffeta Fabric",
"Taffeta Wallpaper",
"Tall Reed Clusters",
"Tapestry Fabric",
"Tapestry Wallpaper",
"Tapestry",
"Tarnished Bronze",
"Tarnished Metal Floor",
"Tarnished Metal",
"Tarnished Silver Texture",
"Tarot Cards",
"Tartan Pattern",
"Tattered Cloth Texture",
"Teak Wood",
"Tencel Fabric",
"Terracotta Clay Flooring",
"Terracotta Floor Tiles",
"Terracotta Wallpaper",
"Terrain Red",
"Terrazzo Wall",
"Terrazzo",
"Textured 70S Wallpaper",
"Textured Acetate",
"Textured Acrylic",
"Textured Ardex",
"Textured Bamboo",
"Textured Basalt",
"Textured Brick Wall",
"Textured Canvas",
"Textured Carpet",
"Textured Cement",
"Textured Ceramic Ground Tiles",
"Textured Ceramic",
"Textured Coir",
"Textured Concrete Ground Tiles",
"Textured Concrete Wall",
"Textured Corduroy",
"Textured Cork",
"Textured Cotton",
"Textured Denim",
"Textured Down",
"Textured Elastomeric",
"Textured Epoxy",
"Textured Fabric Texture",
"Textured Fabric",
"Textured Feather",
"Textured Fleece",
"Textured Foam",
"Textured Fur",
"Textured Glass Wall",
"Textured Glass",
"Textured Gneiss",
"Textured Granodiorite",
"Textured Grasscloth",
"Textured Hay",
"Textured Hdpe",
"Textured Hemp",
"Textured Jute",
"Textured Laminate",
"Textured Ldpe",
"Textured Leather",
"Textured Limestone Flooring",
"Textured Linen",
"Textured Linoleum",
"Textured Marble Flooring",
"Textured Marble Ground Tiles",
"Textured Mdf",
"Textured Melamine",
"Textured Metal Wall",
"Textured Mural",
"Textured Natural Rubber",
"Textured Neoprene",
"Textured Nylon",
"Textured Onyx",
"Textured Paint",
"Textured Papyrus",
"Textured Particleboard",
"Textured Plaster",
"Textured Polycarbonate",
"Textured Polyester",
"Textured Polyfill",
"Textured Polypropylene",
"Textured Polystyrene",
"Textured Polyurethane",
"Textured Porcelain",
"Textured Pvc",
"Textured Quarry",
"Textured Quartz",
"Textured Rattan",
"Textured Rayon",
"Textured Reed",
"Textured Resin",
"Textured Rhyolite",
"Textured Rubber",
"Textured Sandstone Flooring",
"Textured Sandstone",
"Textured Sbr",
"Textured Schist",
"Textured Seagrass",
"Textured Silicone",
"Textured Silk",
"Textured Sisal",
"Textured Slate Flooring",
"Textured Slate",
"Textured Soapstone",
"Textured Steel",
"Textured Stone Wall",
"Textured Straw",
"Textured Stucco",
"Textured Suede",
"Textured Synthetic Fill",
"Textured Synthetic Rubber",
"Textured Tapestry",
"Textured Terrazzo Ground Tiles",
"Textured Travertine Flooring",
"Textured Twill",
"Textured Urethane",
"Textured Velvet",
"Textured Vinyl",
"Textured Wall",
"Textured Wallpaper Wall",
"Textured Wallpaper",
"Textured Wicker",
"Textured Wood Flooring",
"Textured Wood",
"Textured Wooden Wall",
"Thassos Marble",
"Thatch Roof Angled",
"Thermal Fabric",
"Thick Bramble Bushes",
"Thorny Shrubs And Bushes",
"Tie Dye Pattern",
"Tiled Floor",
"Tin Wallpaper",
"Toile Wallpaper",
"Torn Wallpaper Wall",
"Toy Action Figures",
"Toy Animals",
"Toy Cars",
"Toy Construction Vehicles",
"Toy Dolls",
"Toy Food Items",
"Toy Guns",
"Toy Musical Instruments",
"Toy Robots",
"Toy Tools",
"Toy Trains",
"Traditional Terracotta Flooring",
"Translucent Alien Membrane",
"Transparent Glass",
"Transparent Jelly",
"Transparent Water",
"Travertine Gravel",
"Travertine Ground Tiles",
"Travertine Mosaic Ground Tiles",
"Travertine Wall",
"Travertine",
"Tree Bark",
"Tribal Pattern",
"Tribal Wallpaper",
"Tulle Fabric",
"Tumbled Stone Floor Tiles",
"Tumbled Stone Wall",
"Tumbling Blocks Pattern",
"Tweed Fabric",
"Twill Fabric",
"Twill Pattern",
"Twill",
"Twine",
"Twinkling Star Floor",
"Twisted Swamp Branches",
"Twisted Swamp Vegetation",
"Twisted Tree Roots",
"Two-Tone Wood",
"Ubatuba Marble",
"Unicorn Mane Tiles",
"Unstable Swamp Ground",
"Upholstery Fabric",
"Urethane",
"Uv Protective Fabric",
"Velvet Carpet Floor",
"Velvet Fabric",
"Velvet Wallpaper",
"Velvet",
"Victorian Wall",
"Vine Pattern",
"Vintage 70S Wallpaper",
"Vintage Wallpaper",
"Vintage Wood",
"Vinyl Wallpaper",
"Vinyl",
"Voile Fabric",
"Volakas Marble",
"Waffle Fabric",
"Wall Bricks Plaster",
"Wallpaper",
"Walnut Wood",
"Warped Steel Sheet",
"Washers",
"Washi Tape",
"Water-Filled Swamp Craters",
"Waterproof Fabric",
"Watery Surface",
"Wave Wall",
"Wavy Hair Texture",
"Wavy Hair",
"Wavy Marsh Grasses",
"Wavy Ocean Texture",
"Wavy Pattern",
"Wavy River Texture",
"Wavy Seaweed",
"Wavy Swamp Reeds",
"Wavy Swamp Vegetation",
"Wavy Swamp Water Surface",
"Wavy Water Floor",
"Wavy Water Ripple Texture",
"Wavy Water Texture",
"Wavy Water",
"Waxed Wood",
"Waxy Alien Exoskeleton",
"Weathered Brick Floor",
"Weathered Brown Planks",
"Weathered Planks",
"Weathered Steel Plate",
"Weathered Steel",
"Weathered Swamp Trees",
"Weathered Wood",
"Weathered Wooden Wall",
"Wet Soil",
"White Bricks",
"White Gravel",
"White Macaubas Marble",
"White Onyx Marble",
"White Plaster Rough",
"White Plaster",
"White Rough Plaster",
"White Sandstone Blocks",
"White Sandstone Bricks",
"White Wood",
"Whitewashed Wood",
"Wicker",
"Wild Grasses",
"Wildflowers And Grasses",
"Wildflowers",
"Wood Cabinet Worn Long",
"Wood Look Ceramic Tiling",
"Wood Panel 70S Wallpaper",
"Wood Peeling Paint Weathered",
"Wood Plank Flooring",
"Wood Plank Mosaic Tiling",
"Wood Plank Wall",
"Wood Planks Dirt",
"Wood Planks Grey",
"Wood Table Worn",
"Wood Table",
"Wood Wall",
"Wood Wallpaper",
"Wood",
"Wooden Abstract",
"Wooden Accents",
"Wooden Art Deco",
"Wooden Borders",
"Wooden Cabin Floor",
"Wooden Circles",
"Wooden Diamonds",
"Wooden Dragon Ship Bowsprit",
"Wooden Dragon Ship Deck",
"Wooden Dragon Ship Mast",
"Wooden Dragon Ship Rudder",
"Wooden Dragon Ship Walls",
"Wooden Flowers",
"Wooden Geometric",
"Wooden Hexagons",
"Wooden Inlay",
"Wooden Leaves",
"Wooden Medallions",
"Wooden Mosaic Floor Tiles",
"Wooden Mosaic Tiling",
"Wooden Mosaic",
"Wooden Mountains",
"Wooden Ovals",
"Wooden Panels",
"Wooden Parquetry",
"Wooden Pirate Ship Deck",
"Wooden Planks",
"Wooden Rectangles",
"Wooden Rough Planks",
"Wooden Ship Deck",
"Wooden Squares",
"Wooden Stars",
"Wooden Sunbursts",
"Wooden Trees",
"Wooden Triangles",
"Wooden Waves",
"Wool Fabric",
"Word Pattern",
"Wormholes",
"Worn Copper",
"Worn Leather Floor",
"Worn Leather",
"Worn Metal Wall",
"Worn Metal",
"Worn Rock Natural",
"Worn Stonework Wall",
"Worn Stucco Wall",
"Worn Wood",
"Worn Wooden Panel Wall",
"Worn Wooden Wall",
"Woven Fabric",
"Woven Wallpaper",
"Yellow Brick",
"Yellow Bricks",
"Yellow Onyx Marble",
"Yellow Plaster",
"Zebra Wallpaper",
"Zigzag Pattern",
"Zip Ties",
                ]:

                print(material)
                model.cuda()
                # Run the denoising, creating the image (in latent space)
                sample = samplers.EulerASampler(model).sample(
                    clip(material + ", photograph, intricate detail, 4k"), 
                    negative_prompt,
                    768,
                    768,
                    steps=25
                )
                model.cpu()

                print("Decoding")
                images = decoder(sample)
                print("Saving")
                save_images(images, material)

if __name__ == "__main__":
    main()
